import {  ProjectType } from "./projectType.js";

export const Projects: ProjectType[] = [
    {
        id: 'kitchen-remodel',
        name: 'Kitchen Remodel',
        description: 
            'Placeholder description for kitchen remodel project.',
        date: new Date('January 17, 2024'),
        primaryPhoto: '',
        photos: [
            '/../public/kitchen00.jpg',
            '/../public/kitchen01.jpg',
            '/../public/kitchen02.jpg',
            '/../public/kitchen03.jpg',
            '/../public/kitchen04.jpg', 
            '/../public/kitchen05.jpg',
            '/../public/kitchen06.jpg',
            '/../public/kitchen07.jpg',
            '/../public/kitchen08.jpg',
            '/../public/kitchen09.jpg',
            '/../public/kitchen10.jpg', 
        ],
        difficulty: 'Easy',
        time: '2 days',
        tools: [],
        supplies: [],
        cost: 0,
    },
    {
        id: 'cornhole-boards',
        name: 'Cornhole Boards',
        description: '',
        date: new Date('August 5, 2022'),
        primaryPhoto: '',
        photos: [],
        difficulty: 'Easy',
        time: '',
        tools: [],
        supplies: [],
        cost: 0,
    },
    {
        id: 'garden-beds',
        name: 'Garden Beds',
        description: '',
        date: new Date('May 5, 2025'),
        primaryPhoto: '',
        photos: [],
        difficulty: 'Easy',
        time: '',
        tools: [],
        supplies: [],
        cost: 0,
    },
    {
        id: 'bar',
        name: 'Bar',
        description: '',
        date: new Date('May 29, 2022'),
        primaryPhoto: '',
        photos: [],
        difficulty: 'Easy',
        time: '',
        tools: [],
        supplies: [],
        cost: 0,
    },
    {
        id: 'groomsmen-gifts',
        name: 'Groomsmen Gifts',
        description: '',
        date: new Date('August 18, 2022'),
        primaryPhoto: '',
        photos: [],
        difficulty: 'Easy',
        time: '',
        tools: [],
        supplies: [],
        cost: 0,
    },
    {
        id: 'wedding-centerpieces',
        name: 'Wedding Centerpieces',
        description: '',
        date: new Date('August 20, 2022'),
        primaryPhoto: '',
        photos: [],
        difficulty: 'Easy',
        time: '',
        tools: [],
        supplies: [],
        cost: 0,
    }
];